# ####################################
# Created by Astm For MySQL 
# https://github.com/AstmDesign/
# ####################################

INSERT INTO countries('name_ar','name_en') VALUES ('أستراليا','Australia');
INSERT INTO countries('name_ar','name_en') VALUES ('أفغانستان','Afghanistan');
INSERT INTO countries('name_ar','name_en') VALUES ('ألبانيا','Albania');
INSERT INTO countries('name_ar','name_en') VALUES ('أنتيجوا وبربودا','Antigua and Barbuda');
INSERT INTO countries('name_ar','name_en') VALUES ('أنجولا','Angola');
INSERT INTO countries('name_ar','name_en') VALUES ('أندورا','Andorra');
INSERT INTO countries('name_ar','name_en') VALUES ('أيرلندا','Ireland');
INSERT INTO countries('name_ar','name_en') VALUES ('أيسلندا','Iceland');
INSERT INTO countries('name_ar','name_en') VALUES ('اثيوبيا','Ethiopia');
INSERT INTO countries('name_ar','name_en') VALUES ('استونيا','Estonia');
INSERT INTO countries('name_ar','name_en') VALUES ('اسرائيل','Israel');
INSERT INTO countries('name_ar','name_en') VALUES ('الأردن','Jordan');
INSERT INTO countries('name_ar','name_en') VALUES ('الاكوادور','Ecuador');
INSERT INTO countries('name_ar','name_en') VALUES ('الباهاما','Bahamas');
INSERT INTO countries('name_ar','name_en') VALUES ('البحرين','Bahrain');
INSERT INTO countries('name_ar','name_en') VALUES ('البوسنة والهرسك','Bosnia and Herzegovina');
INSERT INTO countries('name_ar','name_en') VALUES ('الجابون','Gabon');
INSERT INTO countries('name_ar','name_en') VALUES ('الدانمرك','Denmark');
INSERT INTO countries('name_ar','name_en') VALUES ('الرأس الأخضر','Cape Verde');
INSERT INTO countries('name_ar','name_en') VALUES ('الصين','China');
INSERT INTO countries('name_ar','name_en') VALUES ('العراق','Iraq');
INSERT INTO countries('name_ar','name_en') VALUES ('القطب الجنوبي','Antarctica');
INSERT INTO countries('name_ar','name_en') VALUES ('الكاميرون','Cameroon');
INSERT INTO countries('name_ar','name_en') VALUES ('الكويت','Kuwait');
INSERT INTO countries('name_ar','name_en') VALUES ('المجر','Hungary');
INSERT INTO countries('name_ar','name_en') VALUES ('المقاطعات الجنوبية الفرنسية','French Southern Territories');
INSERT INTO countries('name_ar','name_en') VALUES ('النمسا','Austria');
INSERT INTO countries('name_ar','name_en') VALUES ('الهند','India');
INSERT INTO countries('name_ar','name_en') VALUES ('اليابان','Japan');
INSERT INTO countries('name_ar','name_en') VALUES ('اندونيسيا','Indonesia');
INSERT INTO countries('name_ar','name_en') VALUES ('ايران','Iran (Islamic Republic of)');
INSERT INTO countries('name_ar','name_en') VALUES ('ايطاليا','Italy');
INSERT INTO countries('name_ar','name_en') VALUES ('بتسوانا','Botswana');
INSERT INTO countries('name_ar','name_en') VALUES ('برمودا','Bermuda');
INSERT INTO countries('name_ar','name_en') VALUES ('بروناي','Brunei Darussalam');
INSERT INTO countries('name_ar','name_en') VALUES ('بلجيكا','Belgium');
INSERT INTO countries('name_ar','name_en') VALUES ('بلغاريا','Bulgaria');
INSERT INTO countries('name_ar','name_en') VALUES ('بنجلاديش','Bangladesh');
INSERT INTO countries('name_ar','name_en') VALUES ('بنين','Benin');
INSERT INTO countries('name_ar','name_en') VALUES ('بوتان','Bhutan');
INSERT INTO countries('name_ar','name_en') VALUES ('بوروندي','Burundi');
INSERT INTO countries('name_ar','name_en') VALUES ('بوليفيا','Bolivia');
INSERT INTO countries('name_ar','name_en') VALUES ('تشاد','Chad');
INSERT INTO countries('name_ar','name_en') VALUES ('ساموا الأمريكية','American Samoa');
INSERT INTO countries('name_ar','name_en') VALUES ('روسيا البيضاء','Belarus');
INSERT INTO countries('name_ar','name_en') VALUES ('جزيرة بوفيه','Bouvet Island');
INSERT INTO countries('name_ar','name_en') VALUES ('كندا','Canada');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر الكايمن','Cayman Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('شيلي','Chile');
INSERT INTO countries('name_ar','name_en') VALUES ('جزيرة الكريسماس','Christmas Island');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر كوكوس','Cocos (Keeling) Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('كولومبيا','Colombia');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر القمر','Comoros');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر كوك','Cook Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('كرواتيا','Croatia (Hrvatska)');
INSERT INTO countries('name_ar','name_en') VALUES ('كوبا','Cuba');
INSERT INTO countries('name_ar','name_en') VALUES ('قبرص','Cyprus');
INSERT INTO countries('name_ar','name_en') VALUES ('جمهورية التشيك','Czech Republic');
INSERT INTO countries('name_ar','name_en') VALUES ('دومينيكا','Dominica');
INSERT INTO countries('name_ar','name_en') VALUES ('جمهورية الدومينيك','Dominican Republic');
INSERT INTO countries('name_ar','name_en') VALUES ('مصر','Egypt');
INSERT INTO countries('name_ar','name_en') VALUES ('غينيا الاستوائية','Equatorial Guinea');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر فوكلاند','Falkland Islands (Malvinas)');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر فارو','Faroe Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('فيجي','Fiji');
INSERT INTO countries('name_ar','name_en') VALUES ('فرنسا','France');
INSERT INTO countries('name_ar','name_en') VALUES ('غويانا','French Guiana');
INSERT INTO countries('name_ar','name_en') VALUES ('غامبيا','Gambia');
INSERT INTO countries('name_ar','name_en') VALUES ('جورجيا','Georgia');
INSERT INTO countries('name_ar','name_en') VALUES ('غانا','Ghana');
INSERT INTO countries('name_ar','name_en') VALUES ('جبل طارق','Gibraltar');
INSERT INTO countries('name_ar','name_en') VALUES ('غيرنسي','Guernsey');
INSERT INTO countries('name_ar','name_en') VALUES ('جرينلاند','Greenland');
INSERT INTO countries('name_ar','name_en') VALUES ('جوادلوب','Guadeloupe');
INSERT INTO countries('name_ar','name_en') VALUES ('جوام','Guam');
INSERT INTO countries('name_ar','name_en') VALUES ('جواتيمالا','Guatemala');
INSERT INTO countries('name_ar','name_en') VALUES ('غينيا','Guinea');
INSERT INTO countries('name_ar','name_en') VALUES ('غيانا','Guyana');
INSERT INTO countries('name_ar','name_en') VALUES ('هايتي','Haiti');
INSERT INTO countries('name_ar','name_en') VALUES ('هندوراس','Honduras');
INSERT INTO countries('name_ar','name_en') VALUES ('هونج كونج الصينية','Hong Kong');
INSERT INTO countries('name_ar','name_en') VALUES ('جزيرة مان','Isle of Man');
INSERT INTO countries('name_ar','name_en') VALUES ('ساحل العاج','Ivory Coast');
INSERT INTO countries('name_ar','name_en') VALUES ('جيرسي','Jersey');
INSERT INTO countries('name_ar','name_en') VALUES ('جامايكا','Jamaica');
INSERT INTO countries('name_ar','name_en') VALUES ('كينيا','Kenya');
INSERT INTO countries('name_ar','name_en') VALUES ('كيريباتي','Kiribati');
INSERT INTO countries('name_ar','name_en') VALUES ('كوريا الشمالية','Korea, Democratic Peoples Republic of');
INSERT INTO countries('name_ar','name_en') VALUES ('كوسوفو','Kosovo');
INSERT INTO countries('name_ar','name_en') VALUES ('قرغيزستان','Kyrgyzstan');
INSERT INTO countries('name_ar','name_en') VALUES ('لاوس','Lao Peoples Democratic Republic');
INSERT INTO countries('name_ar','name_en') VALUES ('لاتفيا','Latvia');
INSERT INTO countries('name_ar','name_en') VALUES ('لبنان','Lebanon');
INSERT INTO countries('name_ar','name_en') VALUES ('ليسوتو','Lesotho');
INSERT INTO countries('name_ar','name_en') VALUES ('أسبانيا','Spain');
INSERT INTO countries('name_ar','name_en') VALUES ('أوزبكستان','Uzbekistan');
INSERT INTO countries('name_ar','name_en') VALUES ('أوغندا','Uganda');
INSERT INTO countries('name_ar','name_en') VALUES ('أوكرانيا','Ukraine');
INSERT INTO countries('name_ar','name_en') VALUES ('البرتغال','Portugal');
INSERT INTO countries('name_ar','name_en') VALUES ('الجبل الأسود','Montenegro');
INSERT INTO countries('name_ar','name_en') VALUES ('السنغال','Senegal');
INSERT INTO countries('name_ar','name_en') VALUES ('السودان','Sudan');
INSERT INTO countries('name_ar','name_en') VALUES ('الصحراء الغربية','Western Sahara');
INSERT INTO countries('name_ar','name_en') VALUES ('الصومال','Somalia');
INSERT INTO countries('name_ar','name_en') VALUES ('الفيلبين','Philippines');
INSERT INTO countries('name_ar','name_en') VALUES ('المغرب','Morocco');
INSERT INTO countries('name_ar','name_en') VALUES ('المكسيك','Mexico');
INSERT INTO countries('name_ar','name_en') VALUES ('المملكة المتحدة','United Kingdom');
INSERT INTO countries('name_ar','name_en') VALUES ('النرويج','Norway');
INSERT INTO countries('name_ar','name_en') VALUES ('النيجر','Niger');
INSERT INTO countries('name_ar','name_en') VALUES ('اليمن','Yemen');
INSERT INTO countries('name_ar','name_en') VALUES ('بابوا غينيا الجديدة','Papua New Guinea');
INSERT INTO countries('name_ar','name_en') VALUES ('باراجواي','Paraguay');
INSERT INTO countries('name_ar','name_en') VALUES ('بالاو','Palau');
INSERT INTO countries('name_ar','name_en') VALUES ('بتكايرن','Pitcairn');
INSERT INTO countries('name_ar','name_en') VALUES ('بنما','Panama');
INSERT INTO countries('name_ar','name_en') VALUES ('بورتوريكو','Puerto Rico');
INSERT INTO countries('name_ar','name_en') VALUES ('بولندا','Poland');
INSERT INTO countries('name_ar','name_en') VALUES ('تانزانيا','Tanzania, United Republic of');
INSERT INTO countries('name_ar','name_en') VALUES ('تايلند','Thailand');
INSERT INTO countries('name_ar','name_en') VALUES ('تايوان','Taiwan');
INSERT INTO countries('name_ar','name_en') VALUES ('تركيا','Turkey');
INSERT INTO countries('name_ar','name_en') VALUES ('ترينيداد وتوباغو','Trinidad and Tobago');
INSERT INTO countries('name_ar','name_en') VALUES ('توجو','Togo');
INSERT INTO countries('name_ar','name_en') VALUES ('توكيلو','Tokelau');
INSERT INTO countries('name_ar','name_en') VALUES ('تونجا','Tonga');
INSERT INTO countries('name_ar','name_en') VALUES ('تونس','Tunisia');
INSERT INTO countries('name_ar','name_en') VALUES ('زامبيا','Zambia');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر والس وفوتونا','Wallis and Futuna Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر فرجين البريطانية','Virgin Islands (British)');
INSERT INTO countries('name_ar','name_en') VALUES ('فيتنام','Vietnam');
INSERT INTO countries('name_ar','name_en') VALUES ('فنزويلا','Venezuela');
INSERT INTO countries('name_ar','name_en') VALUES ('فانواتو','Vanuatu');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر الترك وجايكوس','Turks and Caicos Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('طاجكستان','Tajikistan');
INSERT INTO countries('name_ar','name_en') VALUES ('سوريا','Syrian Arab Republic');
INSERT INTO countries('name_ar','name_en') VALUES ('سويسرا','Switzerland');
INSERT INTO countries('name_ar','name_en') VALUES ('سوازيلاند','Swaziland');
INSERT INTO countries('name_ar','name_en') VALUES ('سورينام','Suriname');
INSERT INTO countries('name_ar','name_en') VALUES ('سانت بيير وميكولون','St. Pierre and Miquelon');
INSERT INTO countries('name_ar','name_en') VALUES ('سانت هيلنا','St. Helena');
INSERT INTO countries('name_ar','name_en') VALUES ('سريلانكا','Sri Lanka');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر سليمان','Solomon Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('جمهورية جنوب افريقيا','South Africa');
INSERT INTO countries('name_ar','name_en') VALUES ('سلوفينيا','Slovenia');
INSERT INTO countries('name_ar','name_en') VALUES ('سنغافورة','Singapore');
INSERT INTO countries('name_ar','name_en') VALUES ('سيراليون','Sierra Leone');
INSERT INTO countries('name_ar','name_en') VALUES ('سيشل','Seychelles');
INSERT INTO countries('name_ar','name_en') VALUES ('صربيا','Serbia');
INSERT INTO countries('name_ar','name_en') VALUES ('سان مارينو','San Marino');
INSERT INTO countries('name_ar','name_en') VALUES ('ساموا','Samoa');
INSERT INTO countries('name_ar','name_en') VALUES ('سانت لوسيا','Saint Lucia');
INSERT INTO countries('name_ar','name_en') VALUES ('سانت كيتس ونيفيس','Saint Kitts and Nevis');
INSERT INTO countries('name_ar','name_en') VALUES ('رواندا','Rwanda');
INSERT INTO countries('name_ar','name_en') VALUES ('روسيا','Russian Federation');
INSERT INTO countries('name_ar','name_en') VALUES ('رومانيا','Romania');
INSERT INTO countries('name_ar','name_en') VALUES ('روينيون','Reunion');
INSERT INTO countries('name_ar','name_en') VALUES ('قطر','Qatar');
INSERT INTO countries('name_ar','name_en') VALUES ('عمان','Oman');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر ماريانا الشمالية','Northern Mariana Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('نيوي','Niue');
INSERT INTO countries('name_ar','name_en') VALUES ('نيجيريا','Nigeria');
INSERT INTO countries('name_ar','name_en') VALUES ('نيكاراجوا','Nicaragua');
INSERT INTO countries('name_ar','name_en') VALUES ('نيوزيلاندا','New Zealand');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر الأنتيل الهولندية','Netherlands Antilles');
INSERT INTO countries('name_ar','name_en') VALUES ('هولندا','Netherlands');
INSERT INTO countries('name_ar','name_en') VALUES ('نيبال','Nepal');
INSERT INTO countries('name_ar','name_en') VALUES ('نورو','Nauru');
INSERT INTO countries('name_ar','name_en') VALUES ('ميانمار','Myanmar');
INSERT INTO countries('name_ar','name_en') VALUES ('موزمبيق','Mozambique');
INSERT INTO countries('name_ar','name_en') VALUES ('مونتسرات','Montserrat');
INSERT INTO countries('name_ar','name_en') VALUES ('موناكو','Monaco');
INSERT INTO countries('name_ar','name_en') VALUES ('مولدافيا','Moldova, Republic of');
INSERT INTO countries('name_ar','name_en') VALUES ('ليبيا','Libyan Arab Jamahiriya');
INSERT INTO countries('name_ar','name_en') VALUES ('ليختنشتاين','Liechtenstein');
INSERT INTO countries('name_ar','name_en') VALUES ('ليتوانيا','Lithuania');
INSERT INTO countries('name_ar','name_en') VALUES ('لوكسمبورج','Luxembourg');
INSERT INTO countries('name_ar','name_en') VALUES ('ماكاو الصينية','Macau');
INSERT INTO countries('name_ar','name_en') VALUES ('مقدونيا','Macedonia');
INSERT INTO countries('name_ar','name_en') VALUES ('ملاوي','Malawi');
INSERT INTO countries('name_ar','name_en') VALUES ('ماليزيا','Malaysia');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر الملديف','Maldives');
INSERT INTO countries('name_ar','name_en') VALUES ('مالي','Mali');
INSERT INTO countries('name_ar','name_en') VALUES ('مالطا','Malta');
INSERT INTO countries('name_ar','name_en') VALUES ('مارتينيك','Martinique');
INSERT INTO countries('name_ar','name_en') VALUES ('موريتانيا','Mauritania');
INSERT INTO countries('name_ar','name_en') VALUES ('موريشيوس','Mauritius');
INSERT INTO countries('name_ar','name_en') VALUES ('مايوت','Mayotte');
INSERT INTO countries('name_ar','name_en') VALUES ('آروبا','Aruba');
INSERT INTO countries('name_ar','name_en') VALUES ('أذربيجان','Azerbaijan');
INSERT INTO countries('name_ar','name_en') VALUES ('ألمانيا','Germany');
INSERT INTO countries('name_ar','name_en') VALUES ('أنجويلا','Anguilla');
INSERT INTO countries('name_ar','name_en') VALUES ('أورجواي','Uruguay');
INSERT INTO countries('name_ar','name_en') VALUES ('اريتريا','Eritrea');
INSERT INTO countries('name_ar','name_en') VALUES ('الأرجنتين','Argentina');
INSERT INTO countries('name_ar','name_en') VALUES ('الامارات العربية المتحدة','United Arab Emirates');
INSERT INTO countries('name_ar','name_en') VALUES ('البرازيل','Brazil');
INSERT INTO countries('name_ar','name_en') VALUES ('الجزائر','Algeria');
INSERT INTO countries('name_ar','name_en') VALUES ('السلفادور','El Salvador');
INSERT INTO countries('name_ar','name_en') VALUES ('السويد','Sweden');
INSERT INTO countries('name_ar','name_en') VALUES ('الفاتيكان','Vatican City State');
INSERT INTO countries('name_ar','name_en') VALUES ('الكونغو - برازافيل','Congo');
INSERT INTO countries('name_ar','name_en') VALUES ('المحيط الهندي البريطاني','British Indian Ocean Territory');
INSERT INTO countries('name_ar','name_en') VALUES ('المملكة العربية السعودية','Saudi Arabia');
INSERT INTO countries('name_ar','name_en') VALUES ('الولايات المتحدة الأمريكية','United States');
INSERT INTO countries('name_ar','name_en') VALUES ('اليونان','Greece');
INSERT INTO countries('name_ar','name_en') VALUES ('باكستان','Pakistan');
INSERT INTO countries('name_ar','name_en') VALUES ('بربادوس','Barbados');
INSERT INTO countries('name_ar','name_en') VALUES ('بليز','Belize');
INSERT INTO countries('name_ar','name_en') VALUES ('بوركينا فاسو','Burkina Faso');
INSERT INTO countries('name_ar','name_en') VALUES ('بولينيزيا الفرنسية','French Polynesia');
INSERT INTO countries('name_ar','name_en') VALUES ('بيرو','Peru');
INSERT INTO countries('name_ar','name_en') VALUES ('تركمانستان','Turkmenistan');
INSERT INTO countries('name_ar','name_en') VALUES ('توفالو','Tuvalu');
INSERT INTO countries('name_ar','name_en') VALUES ('زيمبابوي','Zimbabwe');
INSERT INTO countries('name_ar','name_en') VALUES ('زائير','Zaire');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر فرجين الأمريكية','Virgin Islands (U.S.)');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر الولايات المتحدة البعيدة الصغيرة','United States minor outlying islands');
INSERT INTO countries('name_ar','name_en') VALUES ('سفالبارد وجان مايان','Svalbard and Jan Mayen Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('جورجيا الجنوبية وجزر ساندويتش الجنوبية','South Georgia South Sandwich Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('سلوفاكيا','Slovakia');
INSERT INTO countries('name_ar','name_en') VALUES ('ساو تومي وبرينسيبي','Sao Tome and Principe');
INSERT INTO countries('name_ar','name_en') VALUES ('سانت فنسنت وغرنادين','Saint Vincent and the Grenadines');
INSERT INTO countries('name_ar','name_en') VALUES ('فلسطين','Palestine');
INSERT INTO countries('name_ar','name_en') VALUES ('جزيرة نورفوك','Norfolk Island');
INSERT INTO countries('name_ar','name_en') VALUES ('كاليدونيا الجديدة','New Caledonia');
INSERT INTO countries('name_ar','name_en') VALUES ('ناميبيا','Namibia');
INSERT INTO countries('name_ar','name_en') VALUES ('منغوليا','Mongolia');
INSERT INTO countries('name_ar','name_en') VALUES ('ميكرونيزيا','Micronesia, Federated States of');
INSERT INTO countries('name_ar','name_en') VALUES ('كمبوديا','Cambodia');
INSERT INTO countries('name_ar','name_en') VALUES ('جمهورية افريقيا الوسطى','Central African Republic');
INSERT INTO countries('name_ar','name_en') VALUES ('كوستاريكا','Costa Rica');
INSERT INTO countries('name_ar','name_en') VALUES ('جيبوتي','Djibouti');
INSERT INTO countries('name_ar','name_en') VALUES ('تيمور الشرقية','East Timor');
INSERT INTO countries('name_ar','name_en') VALUES ('فنلندا','Finland');
INSERT INTO countries('name_ar','name_en') VALUES ('فرنسا ، متروبوليتان','France, Metropolitan');
INSERT INTO countries('name_ar','name_en') VALUES ('جرينادا','Grenada');
INSERT INTO countries('name_ar','name_en') VALUES ('غينيا بيساو','Guinea-Bissau');
INSERT INTO countries('name_ar','name_en') VALUES ('جزيرة هيرد وماكدونالد','Heard and Mc Donald Islands');
INSERT INTO countries('name_ar','name_en') VALUES ('كازاخستان','Kazakhstan');
INSERT INTO countries('name_ar','name_en') VALUES ('كوريا الجنوبية','Korea, Republic of');
INSERT INTO countries('name_ar','name_en') VALUES ('ليبيريا','Liberia');
INSERT INTO countries('name_ar','name_en') VALUES ('مدغشقر','Madagascar');
INSERT INTO countries('name_ar','name_en') VALUES ('جزر المارشال','Marshall Islands');
