# ####################################
# Created by Astm For ruby seed file 
# https://github.com/AstmDesign/
# ####################################

Country.create( name_ar: 'أستراليا', name_en: 'Australia', is_published: true )
Country.create( name_ar: 'أفغانستان', name_en: 'Afghanistan', is_published: true )
Country.create( name_ar: 'ألبانيا', name_en: 'Albania', is_published: true )
Country.create( name_ar: 'أنتيجوا وبربودا', name_en: 'Antigua and Barbuda', is_published: true )
Country.create( name_ar: 'أنجولا', name_en: 'Angola', is_published: true )
Country.create( name_ar: 'أندورا', name_en: 'Andorra', is_published: true )
Country.create( name_ar: 'أيرلندا', name_en: 'Ireland', is_published: true )
Country.create( name_ar: 'أيسلندا', name_en: 'Iceland', is_published: true )
Country.create( name_ar: 'اثيوبيا', name_en: 'Ethiopia', is_published: true )
Country.create( name_ar: 'استونيا', name_en: 'Estonia', is_published: true )
Country.create( name_ar: 'اسرائيل', name_en: 'Israel', is_published: true )
Country.create( name_ar: 'الأردن', name_en: 'Jordan', is_published: true )
Country.create( name_ar: 'الاكوادور', name_en: 'Ecuador', is_published: true )
Country.create( name_ar: 'الباهاما', name_en: 'Bahamas', is_published: true )
Country.create( name_ar: 'البحرين', name_en: 'Bahrain', is_published: true )
Country.create( name_ar: 'البوسنة والهرسك', name_en: 'Bosnia and Herzegovina', is_published: true )
Country.create( name_ar: 'الجابون', name_en: 'Gabon', is_published: true )
Country.create( name_ar: 'الدانمرك', name_en: 'Denmark', is_published: true )
Country.create( name_ar: 'الرأس الأخضر', name_en: 'Cape Verde', is_published: true )
Country.create( name_ar: 'الصين', name_en: 'China', is_published: true )
Country.create( name_ar: 'العراق', name_en: 'Iraq', is_published: true )
Country.create( name_ar: 'القطب الجنوبي', name_en: 'Antarctica', is_published: true )
Country.create( name_ar: 'الكاميرون', name_en: 'Cameroon', is_published: true )
Country.create( name_ar: 'الكويت', name_en: 'Kuwait', is_published: true )
Country.create( name_ar: 'المجر', name_en: 'Hungary', is_published: true )
Country.create( name_ar: 'المقاطعات الجنوبية الفرنسية', name_en: 'French Southern Territories', is_published: true )
Country.create( name_ar: 'النمسا', name_en: 'Austria', is_published: true )
Country.create( name_ar: 'الهند', name_en: 'India', is_published: true )
Country.create( name_ar: 'اليابان', name_en: 'Japan', is_published: true )
Country.create( name_ar: 'اندونيسيا', name_en: 'Indonesia', is_published: true )
Country.create( name_ar: 'ايران', name_en: 'Iran (Islamic Republic of)', is_published: true )
Country.create( name_ar: 'ايطاليا', name_en: 'Italy', is_published: true )
Country.create( name_ar: 'بتسوانا', name_en: 'Botswana', is_published: true )
Country.create( name_ar: 'برمودا', name_en: 'Bermuda', is_published: true )
Country.create( name_ar: 'بروناي', name_en: 'Brunei Darussalam', is_published: true )
Country.create( name_ar: 'بلجيكا', name_en: 'Belgium', is_published: true )
Country.create( name_ar: 'بلغاريا', name_en: 'Bulgaria', is_published: true )
Country.create( name_ar: 'بنجلاديش', name_en: 'Bangladesh', is_published: true )
Country.create( name_ar: 'بنين', name_en: 'Benin', is_published: true )
Country.create( name_ar: 'بوتان', name_en: 'Bhutan', is_published: true )
Country.create( name_ar: 'بوروندي', name_en: 'Burundi', is_published: true )
Country.create( name_ar: 'بوليفيا', name_en: 'Bolivia', is_published: true )
Country.create( name_ar: 'تشاد', name_en: 'Chad', is_published: true )
Country.create( name_ar: 'ساموا الأمريكية', name_en: 'American Samoa', is_published: true )
Country.create( name_ar: 'روسيا البيضاء', name_en: 'Belarus', is_published: true )
Country.create( name_ar: 'جزيرة بوفيه', name_en: 'Bouvet Island', is_published: true )
Country.create( name_ar: 'كندا', name_en: 'Canada', is_published: true )
Country.create( name_ar: 'جزر الكايمن', name_en: 'Cayman Islands', is_published: true )
Country.create( name_ar: 'شيلي', name_en: 'Chile', is_published: true )
Country.create( name_ar: 'جزيرة الكريسماس', name_en: 'Christmas Island', is_published: true )
Country.create( name_ar: 'جزر كوكوس', name_en: 'Cocos (Keeling) Islands', is_published: true )
Country.create( name_ar: 'كولومبيا', name_en: 'Colombia', is_published: true )
Country.create( name_ar: 'جزر القمر', name_en: 'Comoros', is_published: true )
Country.create( name_ar: 'جزر كوك', name_en: 'Cook Islands', is_published: true )
Country.create( name_ar: 'كرواتيا', name_en: 'Croatia (Hrvatska)', is_published: true )
Country.create( name_ar: 'كوبا', name_en: 'Cuba', is_published: true )
Country.create( name_ar: 'قبرص', name_en: 'Cyprus', is_published: true )
Country.create( name_ar: 'جمهورية التشيك', name_en: 'Czech Republic', is_published: true )
Country.create( name_ar: 'دومينيكا', name_en: 'Dominica', is_published: true )
Country.create( name_ar: 'جمهورية الدومينيك', name_en: 'Dominican Republic', is_published: true )
Country.create( name_ar: 'مصر', name_en: 'Egypt', is_published: true )
Country.create( name_ar: 'غينيا الاستوائية', name_en: 'Equatorial Guinea', is_published: true )
Country.create( name_ar: 'جزر فوكلاند', name_en: 'Falkland Islands (Malvinas)', is_published: true )
Country.create( name_ar: 'جزر فارو', name_en: 'Faroe Islands', is_published: true )
Country.create( name_ar: 'فيجي', name_en: 'Fiji', is_published: true )
Country.create( name_ar: 'فرنسا', name_en: 'France', is_published: true )
Country.create( name_ar: 'غويانا', name_en: 'French Guiana', is_published: true )
Country.create( name_ar: 'غامبيا', name_en: 'Gambia', is_published: true )
Country.create( name_ar: 'جورجيا', name_en: 'Georgia', is_published: true )
Country.create( name_ar: 'غانا', name_en: 'Ghana', is_published: true )
Country.create( name_ar: 'جبل طارق', name_en: 'Gibraltar', is_published: true )
Country.create( name_ar: 'غيرنسي', name_en: 'Guernsey', is_published: true )
Country.create( name_ar: 'جرينلاند', name_en: 'Greenland', is_published: true )
Country.create( name_ar: 'جوادلوب', name_en: 'Guadeloupe', is_published: true )
Country.create( name_ar: 'جوام', name_en: 'Guam', is_published: true )
Country.create( name_ar: 'جواتيمالا', name_en: 'Guatemala', is_published: true )
Country.create( name_ar: 'غينيا', name_en: 'Guinea', is_published: true )
Country.create( name_ar: 'غيانا', name_en: 'Guyana', is_published: true )
Country.create( name_ar: 'هايتي', name_en: 'Haiti', is_published: true )
Country.create( name_ar: 'هندوراس', name_en: 'Honduras', is_published: true )
Country.create( name_ar: 'هونج كونج الصينية', name_en: 'Hong Kong', is_published: true )
Country.create( name_ar: 'جزيرة مان', name_en: 'Isle of Man', is_published: true )
Country.create( name_ar: 'ساحل العاج', name_en: 'Ivory Coast', is_published: true )
Country.create( name_ar: 'جيرسي', name_en: 'Jersey', is_published: true )
Country.create( name_ar: 'جامايكا', name_en: 'Jamaica', is_published: true )
Country.create( name_ar: 'كينيا', name_en: 'Kenya', is_published: true )
Country.create( name_ar: 'كيريباتي', name_en: 'Kiribati', is_published: true )
Country.create( name_ar: 'كوريا الشمالية', name_en: 'Korea, Democratic Peoples Republic of', is_published: true )
Country.create( name_ar: 'كوسوفو', name_en: 'Kosovo', is_published: true )
Country.create( name_ar: 'قرغيزستان', name_en: 'Kyrgyzstan', is_published: true )
Country.create( name_ar: 'لاوس', name_en: 'Lao Peoples Democratic Republic', is_published: true )
Country.create( name_ar: 'لاتفيا', name_en: 'Latvia', is_published: true )
Country.create( name_ar: 'لبنان', name_en: 'Lebanon', is_published: true )
Country.create( name_ar: 'ليسوتو', name_en: 'Lesotho', is_published: true )
Country.create( name_ar: 'أسبانيا', name_en: 'Spain', is_published: true )
Country.create( name_ar: 'أوزبكستان', name_en: 'Uzbekistan', is_published: true )
Country.create( name_ar: 'أوغندا', name_en: 'Uganda', is_published: true )
Country.create( name_ar: 'أوكرانيا', name_en: 'Ukraine', is_published: true )
Country.create( name_ar: 'البرتغال', name_en: 'Portugal', is_published: true )
Country.create( name_ar: 'الجبل الأسود', name_en: 'Montenegro', is_published: true )
Country.create( name_ar: 'السنغال', name_en: 'Senegal', is_published: true )
Country.create( name_ar: 'السودان', name_en: 'Sudan', is_published: true )
Country.create( name_ar: 'الصحراء الغربية', name_en: 'Western Sahara', is_published: true )
Country.create( name_ar: 'الصومال', name_en: 'Somalia', is_published: true )
Country.create( name_ar: 'الفيلبين', name_en: 'Philippines', is_published: true )
Country.create( name_ar: 'المغرب', name_en: 'Morocco', is_published: true )
Country.create( name_ar: 'المكسيك', name_en: 'Mexico', is_published: true )
Country.create( name_ar: 'المملكة المتحدة', name_en: 'United Kingdom', is_published: true )
Country.create( name_ar: 'النرويج', name_en: 'Norway', is_published: true )
Country.create( name_ar: 'النيجر', name_en: 'Niger', is_published: true )
Country.create( name_ar: 'اليمن', name_en: 'Yemen', is_published: true )
Country.create( name_ar: 'بابوا غينيا الجديدة', name_en: 'Papua New Guinea', is_published: true )
Country.create( name_ar: 'باراجواي', name_en: 'Paraguay', is_published: true )
Country.create( name_ar: 'بالاو', name_en: 'Palau', is_published: true )
Country.create( name_ar: 'بتكايرن', name_en: 'Pitcairn', is_published: true )
Country.create( name_ar: 'بنما', name_en: 'Panama', is_published: true )
Country.create( name_ar: 'بورتوريكو', name_en: 'Puerto Rico', is_published: true )
Country.create( name_ar: 'بولندا', name_en: 'Poland', is_published: true )
Country.create( name_ar: 'تانزانيا', name_en: 'Tanzania, United Republic of', is_published: true )
Country.create( name_ar: 'تايلند', name_en: 'Thailand', is_published: true )
Country.create( name_ar: 'تايوان', name_en: 'Taiwan', is_published: true )
Country.create( name_ar: 'تركيا', name_en: 'Turkey', is_published: true )
Country.create( name_ar: 'ترينيداد وتوباغو', name_en: 'Trinidad and Tobago', is_published: true )
Country.create( name_ar: 'توجو', name_en: 'Togo', is_published: true )
Country.create( name_ar: 'توكيلو', name_en: 'Tokelau', is_published: true )
Country.create( name_ar: 'تونجا', name_en: 'Tonga', is_published: true )
Country.create( name_ar: 'تونس', name_en: 'Tunisia', is_published: true )
Country.create( name_ar: 'زامبيا', name_en: 'Zambia', is_published: true )
Country.create( name_ar: 'جزر والس وفوتونا', name_en: 'Wallis and Futuna Islands', is_published: true )
Country.create( name_ar: 'جزر فرجين البريطانية', name_en: 'Virgin Islands (British)', is_published: true )
Country.create( name_ar: 'فيتنام', name_en: 'Vietnam', is_published: true )
Country.create( name_ar: 'فنزويلا', name_en: 'Venezuela', is_published: true )
Country.create( name_ar: 'فانواتو', name_en: 'Vanuatu', is_published: true )
Country.create( name_ar: 'جزر الترك وجايكوس', name_en: 'Turks and Caicos Islands', is_published: true )
Country.create( name_ar: 'طاجكستان', name_en: 'Tajikistan', is_published: true )
Country.create( name_ar: 'سوريا', name_en: 'Syrian Arab Republic', is_published: true )
Country.create( name_ar: 'سويسرا', name_en: 'Switzerland', is_published: true )
Country.create( name_ar: 'سوازيلاند', name_en: 'Swaziland', is_published: true )
Country.create( name_ar: 'سورينام', name_en: 'Suriname', is_published: true )
Country.create( name_ar: 'سانت بيير وميكولون', name_en: 'St. Pierre and Miquelon', is_published: true )
Country.create( name_ar: 'سانت هيلنا', name_en: 'St. Helena', is_published: true )
Country.create( name_ar: 'سريلانكا', name_en: 'Sri Lanka', is_published: true )
Country.create( name_ar: 'جزر سليمان', name_en: 'Solomon Islands', is_published: true )
Country.create( name_ar: 'جمهورية جنوب افريقيا', name_en: 'South Africa', is_published: true )
Country.create( name_ar: 'سلوفينيا', name_en: 'Slovenia', is_published: true )
Country.create( name_ar: 'سنغافورة', name_en: 'Singapore', is_published: true )
Country.create( name_ar: 'سيراليون', name_en: 'Sierra Leone', is_published: true )
Country.create( name_ar: 'سيشل', name_en: 'Seychelles', is_published: true )
Country.create( name_ar: 'صربيا', name_en: 'Serbia', is_published: true )
Country.create( name_ar: 'سان مارينو', name_en: 'San Marino', is_published: true )
Country.create( name_ar: 'ساموا', name_en: 'Samoa', is_published: true )
Country.create( name_ar: 'سانت لوسيا', name_en: 'Saint Lucia', is_published: true )
Country.create( name_ar: 'سانت كيتس ونيفيس', name_en: 'Saint Kitts and Nevis', is_published: true )
Country.create( name_ar: 'رواندا', name_en: 'Rwanda', is_published: true )
Country.create( name_ar: 'روسيا', name_en: 'Russian Federation', is_published: true )
Country.create( name_ar: 'رومانيا', name_en: 'Romania', is_published: true )
Country.create( name_ar: 'روينيون', name_en: 'Reunion', is_published: true )
Country.create( name_ar: 'قطر', name_en: 'Qatar', is_published: true )
Country.create( name_ar: 'عمان', name_en: 'Oman', is_published: true )
Country.create( name_ar: 'جزر ماريانا الشمالية', name_en: 'Northern Mariana Islands', is_published: true )
Country.create( name_ar: 'نيوي', name_en: 'Niue', is_published: true )
Country.create( name_ar: 'نيجيريا', name_en: 'Nigeria', is_published: true )
Country.create( name_ar: 'نيكاراجوا', name_en: 'Nicaragua', is_published: true )
Country.create( name_ar: 'نيوزيلاندا', name_en: 'New Zealand', is_published: true )
Country.create( name_ar: 'جزر الأنتيل الهولندية', name_en: 'Netherlands Antilles', is_published: true )
Country.create( name_ar: 'هولندا', name_en: 'Netherlands', is_published: true )
Country.create( name_ar: 'نيبال', name_en: 'Nepal', is_published: true )
Country.create( name_ar: 'نورو', name_en: 'Nauru', is_published: true )
Country.create( name_ar: 'ميانمار', name_en: 'Myanmar', is_published: true )
Country.create( name_ar: 'موزمبيق', name_en: 'Mozambique', is_published: true )
Country.create( name_ar: 'مونتسرات', name_en: 'Montserrat', is_published: true )
Country.create( name_ar: 'موناكو', name_en: 'Monaco', is_published: true )
Country.create( name_ar: 'مولدافيا', name_en: 'Moldova, Republic of', is_published: true )
Country.create( name_ar: 'ليبيا', name_en: 'Libyan Arab Jamahiriya', is_published: true )
Country.create( name_ar: 'ليختنشتاين', name_en: 'Liechtenstein', is_published: true )
Country.create( name_ar: 'ليتوانيا', name_en: 'Lithuania', is_published: true )
Country.create( name_ar: 'لوكسمبورج', name_en: 'Luxembourg', is_published: true )
Country.create( name_ar: 'ماكاو الصينية', name_en: 'Macau', is_published: true )
Country.create( name_ar: 'مقدونيا', name_en: 'Macedonia', is_published: true )
Country.create( name_ar: 'ملاوي', name_en: 'Malawi', is_published: true )
Country.create( name_ar: 'ماليزيا', name_en: 'Malaysia', is_published: true )
Country.create( name_ar: 'جزر الملديف', name_en: 'Maldives', is_published: true )
Country.create( name_ar: 'مالي', name_en: 'Mali', is_published: true )
Country.create( name_ar: 'مالطا', name_en: 'Malta', is_published: true )
Country.create( name_ar: 'مارتينيك', name_en: 'Martinique', is_published: true )
Country.create( name_ar: 'موريتانيا', name_en: 'Mauritania', is_published: true )
Country.create( name_ar: 'موريشيوس', name_en: 'Mauritius', is_published: true )
Country.create( name_ar: 'مايوت', name_en: 'Mayotte', is_published: true )
Country.create( name_ar: 'آروبا', name_en: 'Aruba', is_published: true )
Country.create( name_ar: 'أذربيجان', name_en: 'Azerbaijan', is_published: true )
Country.create( name_ar: 'ألمانيا', name_en: 'Germany', is_published: true )
Country.create( name_ar: 'أنجويلا', name_en: 'Anguilla', is_published: true )
Country.create( name_ar: 'أورجواي', name_en: 'Uruguay', is_published: true )
Country.create( name_ar: 'اريتريا', name_en: 'Eritrea', is_published: true )
Country.create( name_ar: 'الأرجنتين', name_en: 'Argentina', is_published: true )
Country.create( name_ar: 'الامارات العربية المتحدة', name_en: 'United Arab Emirates', is_published: true )
Country.create( name_ar: 'البرازيل', name_en: 'Brazil', is_published: true )
Country.create( name_ar: 'الجزائر', name_en: 'Algeria', is_published: true )
Country.create( name_ar: 'السلفادور', name_en: 'El Salvador', is_published: true )
Country.create( name_ar: 'السويد', name_en: 'Sweden', is_published: true )
Country.create( name_ar: 'الفاتيكان', name_en: 'Vatican City State', is_published: true )
Country.create( name_ar: 'الكونغو - برازافيل', name_en: 'Congo', is_published: true )
Country.create( name_ar: 'المحيط الهندي البريطاني', name_en: 'British Indian Ocean Territory', is_published: true )
Country.create( name_ar: 'المملكة العربية السعودية', name_en: 'Saudi Arabia', is_published: true )
Country.create( name_ar: 'الولايات المتحدة الأمريكية', name_en: 'United States', is_published: true )
Country.create( name_ar: 'اليونان', name_en: 'Greece', is_published: true )
Country.create( name_ar: 'باكستان', name_en: 'Pakistan', is_published: true )
Country.create( name_ar: 'بربادوس', name_en: 'Barbados', is_published: true )
Country.create( name_ar: 'بليز', name_en: 'Belize', is_published: true )
Country.create( name_ar: 'بوركينا فاسو', name_en: 'Burkina Faso', is_published: true )
Country.create( name_ar: 'بولينيزيا الفرنسية', name_en: 'French Polynesia', is_published: true )
Country.create( name_ar: 'بيرو', name_en: 'Peru', is_published: true )
Country.create( name_ar: 'تركمانستان', name_en: 'Turkmenistan', is_published: true )
Country.create( name_ar: 'توفالو', name_en: 'Tuvalu', is_published: true )
Country.create( name_ar: 'زيمبابوي', name_en: 'Zimbabwe', is_published: true )
Country.create( name_ar: 'زائير', name_en: 'Zaire', is_published: true )
Country.create( name_ar: 'جزر فرجين الأمريكية', name_en: 'Virgin Islands (U.S.)', is_published: true )
Country.create( name_ar: 'جزر الولايات المتحدة البعيدة الصغيرة', name_en: 'United States minor outlying islands', is_published: true )
Country.create( name_ar: 'سفالبارد وجان مايان', name_en: 'Svalbard and Jan Mayen Islands', is_published: true )
Country.create( name_ar: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', name_en: 'South Georgia South Sandwich Islands', is_published: true )
Country.create( name_ar: 'سلوفاكيا', name_en: 'Slovakia', is_published: true )
Country.create( name_ar: 'ساو تومي وبرينسيبي', name_en: 'Sao Tome and Principe', is_published: true )
Country.create( name_ar: 'سانت فنسنت وغرنادين', name_en: 'Saint Vincent and the Grenadines', is_published: true )
Country.create( name_ar: 'فلسطين', name_en: 'Palestine', is_published: true )
Country.create( name_ar: 'جزيرة نورفوك', name_en: 'Norfolk Island', is_published: true )
Country.create( name_ar: 'كاليدونيا الجديدة', name_en: 'New Caledonia', is_published: true )
Country.create( name_ar: 'ناميبيا', name_en: 'Namibia', is_published: true )
Country.create( name_ar: 'منغوليا', name_en: 'Mongolia', is_published: true )
Country.create( name_ar: 'ميكرونيزيا', name_en: 'Micronesia, Federated States of', is_published: true )
Country.create( name_ar: 'كمبوديا', name_en: 'Cambodia', is_published: true )
Country.create( name_ar: 'جمهورية افريقيا الوسطى', name_en: 'Central African Republic', is_published: true )
Country.create( name_ar: 'كوستاريكا', name_en: 'Costa Rica', is_published: true )
Country.create( name_ar: 'جيبوتي', name_en: 'Djibouti', is_published: true )
Country.create( name_ar: 'تيمور الشرقية', name_en: 'East Timor', is_published: true )
Country.create( name_ar: 'فنلندا', name_en: 'Finland', is_published: true )
Country.create( name_ar: 'فرنسا ، متروبوليتان', name_en: 'France, Metropolitan', is_published: true )
Country.create( name_ar: 'جرينادا', name_en: 'Grenada', is_published: true )
Country.create( name_ar: 'غينيا بيساو', name_en: 'Guinea-Bissau', is_published: true )
Country.create( name_ar: 'جزيرة هيرد وماكدونالد', name_en: 'Heard and Mc Donald Islands', is_published: true )
Country.create( name_ar: 'كازاخستان', name_en: 'Kazakhstan', is_published: true )
Country.create( name_ar: 'كوريا الجنوبية', name_en: 'Korea, Republic of', is_published: true )
Country.create( name_ar: 'ليبيريا', name_en: 'Liberia', is_published: true )
Country.create( name_ar: 'مدغشقر', name_en: 'Madagascar', is_published: true )
Country.create( name_ar: 'جزر المارشال', name_en: 'Marshall Islands', is_published: true )
