# ####################################
# Created by Astm For ruby seed file 
# https://github.com/AstmDesign/
# ####################################

Country.create( name_ar: 'أستراليا', name_en: 'Australia', code: 'AU', currency: 'AUD', utc_time: '+09:30', is_published: true )
Country.create( name_ar: 'أفغانستان', name_en: 'Afghanistan', code: 'AF', currency: 'AFN', utc_time: '+04:30', is_published: true )
Country.create( name_ar: 'ألبانيا', name_en: 'Albania', code: 'AL', currency: 'ALL', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'أنتيجوا وبربودا', name_en: 'Antigua and Barbuda', code: 'AG', currency: 'XCD', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'أنجولا', name_en: 'Angola', code: 'AO', currency: 'AOA', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'أندورا', name_en: 'Andorra', code: 'AD', currency: 'EUR', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'أيرلندا', name_en: 'Ireland', code: 'IE', currency: 'EUR', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'أيسلندا', name_en: 'Iceland', code: 'IS', currency: 'ISK', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'اثيوبيا', name_en: 'Ethiopia', code: 'ET', currency: 'ETB', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'استونيا', name_en: 'Estonia', code: 'EE', currency: 'EUR', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'اسرائيل', name_en: 'Israel', code: 'IL', currency: 'ILS', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'الأردن', name_en: 'Jordan', code: 'JO', currency: 'JOD', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'الاكوادور', name_en: 'Ecuador', code: 'EC', currency: 'USD', utc_time: '−05:00', is_published: true )
Country.create( name_ar: 'الباهاما', name_en: 'Bahamas', code: 'BS', currency: 'BSD', utc_time: '−05:00', is_published: true )
Country.create( name_ar: 'البحرين', name_en: 'Bahrain', code: 'BH', currency: 'BHD', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'البوسنة والهرسك', name_en: 'Bosnia and Herzegovina', code: 'BA', currency: 'BAM', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'الجابون', name_en: 'Gabon', code: 'GA', currency: 'XAF', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'الدانمرك', name_en: 'Denmark', code: 'DK', currency: 'DKK', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'الرأس الأخضر', name_en: 'Cape Verde', code: 'CV', currency: 'CVE', utc_time: '−01:00', is_published: true )
Country.create( name_ar: 'الصين', name_en: 'China', code: 'CN', currency: 'CNY', utc_time: '+08:00', is_published: true )
Country.create( name_ar: 'العراق', name_en: 'Iraq', code: 'IQ', currency: 'IQD', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'القطب الجنوبي', name_en: 'Antarctica', code: 'AQ', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'الكاميرون', name_en: 'Cameroon', code: 'CM', currency: 'XAF', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'الكويت', name_en: 'Kuwait', code: 'KW', currency: 'KWD', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'المجر', name_en: 'Hungary', code: 'HU', currency: 'HUF', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'المقاطعات الجنوبية الفرنسية', name_en: 'French Southern Territories', code: 'TF', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'النمسا', name_en: 'Austria', code: 'AT', currency: 'EUR', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'الهند', name_en: 'India', code: 'IN', currency: 'INR', utc_time: '+05:30', is_published: true )
Country.create( name_ar: 'اليابان', name_en: 'Japan', code: 'JP', currency: 'JPY', utc_time: '+09:00', is_published: true )
Country.create( name_ar: 'اندونيسيا', name_en: 'Indonesia', code: 'ID', currency: 'IDR', utc_time: '+08:00', is_published: true )
Country.create( name_ar: 'ايران', name_en: 'Iran', code: 'IR', currency: 'IRR', utc_time: '+03:30', is_published: true )
Country.create( name_ar: 'ايطاليا', name_en: 'Italy', code: 'IT', currency: 'EUR', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'بتسوانا', name_en: 'Botswana', code: 'BW', currency: 'BWP', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'برمودا', name_en: 'Bermuda', code: 'BM', currency: 'BMD', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'بروناي', name_en: 'Brunei Darussalam', code: 'BN', currency: 'BND', utc_time: '+08:00', is_published: true )
Country.create( name_ar: 'بلجيكا', name_en: 'Belgium', code: 'BE', currency: 'EUR', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'بلغاريا', name_en: 'Bulgaria', code: 'BG', currency: 'BGN', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'بنجلاديش', name_en: 'Bangladesh', code: 'BD', currency: 'BDT', utc_time: '+06:00', is_published: true )
Country.create( name_ar: 'بنين', name_en: 'Benin', code: 'BJ', currency: 'XOF', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'بوتان', name_en: 'Bhutan', code: 'BT', currency: 'BTN', utc_time: '+06:00', is_published: true )
Country.create( name_ar: 'بوروندي', name_en: 'Burundi', code: 'BI', currency: 'BIF', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'بوليفيا', name_en: 'Bolivia', code: 'BO', currency: 'BOB', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'تشاد', name_en: 'Chad', code: 'TD', currency: 'XAF', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'ساموا الأمريكية', name_en: 'American Samoa', code: 'AS', currency: 'USD', utc_time: '−11:00', is_published: true )
Country.create( name_ar: 'روسيا البيضاء', name_en: 'Belarus', code: 'BY', currency: 'BYN', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'جزيرة بوفيه', name_en: 'Bouvet Island', code: 'BV', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'كندا', name_en: 'Canada', code: 'CA', currency: 'CAD', utc_time: '-05:00', is_published: true )
Country.create( name_ar: 'جزر الكايمن', name_en: 'Cayman Islands', code: 'KY', currency: 'KYD', utc_time: '−05:00', is_published: true )
Country.create( name_ar: 'شيلي', name_en: 'Chile', code: 'CL', currency: 'CLP', utc_time: '−03:00', is_published: true )
Country.create( name_ar: 'جزيرة الكريسماس', name_en: 'Christmas Island', code: 'CX', currency: 'AUD', utc_time: '+07:00', is_published: true )
Country.create( name_ar: 'جزر كوكوس', name_en: 'Cocos (Keeling) Islands', code: 'CC', currency: 'AUD', utc_time: '+06:30', is_published: true )
Country.create( name_ar: 'كولومبيا', name_en: 'Colombia', code: 'CO', currency: 'COP', utc_time: '−05:00', is_published: true )
Country.create( name_ar: 'جزر القمر', name_en: 'Comoros', code: 'KM', currency: '', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'جزر كوك', name_en: 'Cook Islands', code: 'CK', currency: '', utc_time: '−10:00', is_published: true )
Country.create( name_ar: 'كرواتيا', name_en: 'Croatia (Hrvatska)', code: 'HR', currency: 'HRK', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'كوبا', name_en: 'Cuba', code: 'CU', currency: 'CUP', utc_time: '−05:00', is_published: true )
Country.create( name_ar: 'قبرص', name_en: 'Cyprus', code: 'CY', currency: 'EUR', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'جمهورية التشيك', name_en: 'Czech Republic', code: '	CZ', currency: 'CZK', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'دومينيكا', name_en: 'Dominica', code: 'DM', currency: 'XCD', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'جمهورية الدومينيك', name_en: 'Dominican Republic', code: 'DO', currency: 'DOP', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'مصر', name_en: 'Egypt', code: 'EG', currency: 'EGP', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'غينيا الاستوائية', name_en: 'Equatorial Guinea', code: 'GQ', currency: 'XAF', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'جزر فوكلاند', name_en: 'Falkland Islands (Malvinas)', code: 'FK', currency: 'FKP', utc_time: '−03:00', is_published: true )
Country.create( name_ar: 'جزر فارو', name_en: 'Faroe Islands', code: 'FO', currency: '', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'فيجي', name_en: 'Fiji', code: 'FJ', currency: 'FJD', utc_time: '+12:00', is_published: true )
Country.create( name_ar: 'فرنسا', name_en: 'France', code: 'FR', currency: 'EUR', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'غويانا', name_en: 'French Guiana', code: 'GF', currency: 'EUR', utc_time: '−03:00', is_published: true )
Country.create( name_ar: 'غامبيا', name_en: 'Gambia', code: 'GM', currency: 'GMD', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'جورجيا', name_en: 'Georgia', code: 'GE', currency: 'GEL', utc_time: '−02:00', is_published: true )
Country.create( name_ar: 'غانا', name_en: 'Ghana', code: 'GH', currency: 'GHS', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'جبل طارق', name_en: 'Gibraltar', code: 'GI', currency: 'GIP', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'غيرنسي', name_en: 'Guernsey', code: 'GG', currency: 'GGP', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'جرينلاند', name_en: 'Greenland', code: 'GL', currency: 'DKK', utc_time: '−03:00', is_published: true )
Country.create( name_ar: 'جوادلوب', name_en: 'Guadeloupe', code: 'GP', currency: 'EUR', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'جوام', name_en: 'Guam', code: 'GU', currency: 'USD', utc_time: '+10:00', is_published: true )
Country.create( name_ar: 'جواتيمالا', name_en: 'Guatemala', code: 'GT', currency: 'GTQ', utc_time: '−06:00', is_published: true )
Country.create( name_ar: 'غينيا', name_en: 'Guinea', code: 'GN', currency: 'GNF', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'غيانا', name_en: 'Guyana', code: 'GY', currency: 'GYD', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'هايتي', name_en: 'Haiti', code: 'HT', currency: 'HTG', utc_time: '−05:00', is_published: true )
Country.create( name_ar: 'هندوراس', name_en: 'Honduras', code: 'HN', currency: 'HNL', utc_time: '−06:00', is_published: true )
Country.create( name_ar: 'هونج كونج الصينية', name_en: 'Hong Kong', code: 'HK', currency: 'HKD', utc_time: '+08:00', is_published: true )
Country.create( name_ar: 'جزيرة مان', name_en: 'Isle of Man', code: 'IM', currency: 'IMP', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'ساحل العاج', name_en: 'Cote dIvoire', code: 'CI', currency: 'XOF', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'جيرسي', name_en: 'Jersey', code: 'JE', currency: 'JEP', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'جامايكا', name_en: 'Jamaica', code: 'JM', currency: 'JMD', utc_time: '−05:00', is_published: true )
Country.create( name_ar: 'كينيا', name_en: 'Kenya', code: 'KE', currency: 'KES', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'كيريباتي', name_en: 'Kiribati', code: 'KI', currency: 'AUD', utc_time: '+13:00', is_published: true )
Country.create( name_ar: 'كوريا الشمالية', name_en: 'Korea, Democratic Peoples Republic of', code: 'KP', currency: 'KPW', utc_time: '+09:00', is_published: true )
Country.create( name_ar: 'كوسوفو', name_en: 'Kosovo', code: 'RKS', currency: 'EUR', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'قرغيزستان', name_en: 'Kyrgyzstan', code: 'KG', currency: 'KGS', utc_time: '+06:00', is_published: true )
Country.create( name_ar: 'لاوس', name_en: 'Lao Peoples Democratic Republic', code: 'LA', currency: 'LAK', utc_time: '+07:00', is_published: true )
Country.create( name_ar: 'لاتفيا', name_en: 'Latvia', code: 'LV', currency: 'EUR', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'لبنان', name_en: 'Lebanon', code: 'LB', currency: 'LBP', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'ليسوتو', name_en: 'Lesotho', code: 'LS', currency: 'LSL', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'أسبانيا', name_en: 'Spain', code: 'ES', currency: 'EUR', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'أوزبكستان', name_en: 'Uzbekistan', code: 'UZ', currency: 'UZS', utc_time: '+05:00', is_published: true )
Country.create( name_ar: 'أوغندا', name_en: 'Uganda', code: 'UG', currency: 'UGX', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'أوكرانيا', name_en: 'Ukraine', code: 'UA', currency: 'UAH', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'البرتغال', name_en: 'Portugal', code: 'PT', currency: 'EUR', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'الجبل الأسود', name_en: 'Montenegro', code: 'ME', currency: 'EUR', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'السنغال', name_en: 'Senegal', code: 'SN', currency: 'XOF', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'السودان', name_en: 'Sudan', code: 'SD', currency: 'SDG', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'الصحراء الغربية', name_en: 'Western Sahara', code: 'EH', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'الصومال', name_en: 'Somalia', code: 'SO', currency: 'SOS', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'الفيلبين', name_en: 'Philippines', code: 'PH', currency: 'PHP', utc_time: '+08:00', is_published: true )
Country.create( name_ar: 'المغرب', name_en: 'Morocco', code: 'MA', currency: 'MAD', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'المكسيك', name_en: 'Mexico', code: 'MX', currency: 'MXN', utc_time: '−07:00', is_published: true )
Country.create( name_ar: 'المملكة المتحدة', name_en: 'United Kingdom', code: 'GB', currency: 'GBP', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'النرويج', name_en: 'Norway', code: 'NO', currency: 'NOK', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'النيجر', name_en: 'Niger', code: 'NE', currency: 'XOF', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'اليمن', name_en: 'Yemen', code: 'YE', currency: 'YER', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'بابوا غينيا الجديدة', name_en: 'Papua New Guinea', code: 'PG', currency: 'PGK', utc_time: '+10:00', is_published: true )
Country.create( name_ar: 'باراجواي', name_en: 'Paraguay', code: 'PY', currency: 'PYG', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'بالاو', name_en: 'Palau', code: 'PW', currency: 'USD', utc_time: '+09:00', is_published: true )
Country.create( name_ar: 'بتكايرن', name_en: 'Pitcairn', code: 'PN', currency: 'NZD', utc_time: '−08:00', is_published: true )
Country.create( name_ar: 'بنما', name_en: 'Panama', code: 'PA', currency: 'USD', utc_time: '−05:00', is_published: true )
Country.create( name_ar: 'بورتوريكو', name_en: 'Puerto Rico', code: 'PR', currency: 'USD', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'بولندا', name_en: 'Poland', code: 'PL', currency: 'PLN', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'تانزانيا', name_en: 'Tanzania, United Republic of', code: 'TZ', currency: 'TZS', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'تايلند', name_en: 'Thailand', code: 'TH', currency: 'THB', utc_time: '+07:00', is_published: true )
Country.create( name_ar: 'تايوان', name_en: 'Taiwan', code: 'TW', currency: 'TWD', utc_time: '+08:00', is_published: true )
Country.create( name_ar: 'تركيا', name_en: 'Turkey', code: 'TR', currency: 'TRY', utc_time: '+03:00', is_published: true )
Country.create( name_ar: 'ترينيداد وتوباغو', name_en: 'Trinidad and Tobago', code: 'TT', currency: 'TTD', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'توجو', name_en: 'Togo', code: 'TG', currency: 'XOF', utc_time: '00:00', is_published: true )
Country.create( name_ar: 'توكيلو', name_en: 'Tokelau', code: 'TK', currency: 'NZD', utc_time: '+13:00', is_published: true )
Country.create( name_ar: 'تونجا', name_en: 'Tonga', code: 'TO', currency: 'TOP', utc_time: '+13:00', is_published: true )
Country.create( name_ar: 'تونس', name_en: 'Tunisia', code: 'TN', currency: 'TND', utc_time: '+01:00', is_published: true )
Country.create( name_ar: 'زامبيا', name_en: 'Zambia', code: 'ZM', currency: 'ZMW', utc_time: '+02:00', is_published: true )
Country.create( name_ar: 'جزر والس وفوتونا', name_en: 'Wallis and Futuna Islands', code: 'WF', currency: 'XPF', utc_time: '+12:00', is_published: true )
Country.create( name_ar: 'جزر فرجين البريطانية', name_en: 'Virgin Islands (British)', code: 'VG', currency: 'USD', utc_time: '−04:00', is_published: true )
Country.create( name_ar: 'فيتنام', name_en: 'Vietnam', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'فنزويلا', name_en: 'Venezuela', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'فانواتو', name_en: 'Vanuatu', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزر الترك وجايكوس', name_en: 'Turks and Caicos Islands', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'طاجكستان', name_en: 'Tajikistan', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سوريا', name_en: 'Syrian Arab Republic', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سويسرا', name_en: 'Switzerland', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سوازيلاند', name_en: 'Swaziland', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سورينام', name_en: 'Suriname', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سانت بيير وميكولون', name_en: 'St. Pierre and Miquelon', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سانت هيلنا', name_en: 'St. Helena', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سريلانكا', name_en: 'Sri Lanka', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزر سليمان', name_en: 'Solomon Islands', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جمهورية جنوب افريقيا', name_en: 'South Africa', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سلوفينيا', name_en: 'Slovenia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سنغافورة', name_en: 'Singapore', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سيراليون', name_en: 'Sierra Leone', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سيشل', name_en: 'Seychelles', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'صربيا', name_en: 'Serbia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سان مارينو', name_en: 'San Marino', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ساموا', name_en: 'Samoa', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سانت لوسيا', name_en: 'Saint Lucia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سانت كيتس ونيفيس', name_en: 'Saint Kitts and Nevis', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'رواندا', name_en: 'Rwanda', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'روسيا', name_en: 'Russian Federation', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'رومانيا', name_en: 'Romania', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'روينيون', name_en: 'Reunion', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'قطر', name_en: 'Qatar', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'عمان', name_en: 'Oman', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزر ماريانا الشمالية', name_en: 'Northern Mariana Islands', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'نيوي', name_en: 'Niue', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'نيجيريا', name_en: 'Nigeria', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'نيكاراجوا', name_en: 'Nicaragua', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'نيوزيلاندا', name_en: 'New Zealand', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزر الأنتيل الهولندية', name_en: 'Netherlands Antilles', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'هولندا', name_en: 'Netherlands', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'نيبال', name_en: 'Nepal', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'نورو', name_en: 'Nauru', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ميانمار', name_en: 'Myanmar', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'موزمبيق', name_en: 'Mozambique', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'مونتسرات', name_en: 'Montserrat', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'موناكو', name_en: 'Monaco', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'مولدافيا', name_en: 'Moldova, Republic of', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ليبيا', name_en: 'Libyan Arab Jamahiriya', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ليختنشتاين', name_en: 'Liechtenstein', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ليتوانيا', name_en: 'Lithuania', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'لوكسمبورج', name_en: 'Luxembourg', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ماكاو الصينية', name_en: 'Macau', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'مقدونيا', name_en: 'Macedonia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ملاوي', name_en: 'Malawi', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ماليزيا', name_en: 'Malaysia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزر الملديف', name_en: 'Maldives', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'مالي', name_en: 'Mali', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'مالطا', name_en: 'Malta', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'مارتينيك', name_en: 'Martinique', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'موريتانيا', name_en: 'Mauritania', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'موريشيوس', name_en: 'Mauritius', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'مايوت', name_en: 'Mayotte', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'آروبا', name_en: 'Aruba', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'أذربيجان', name_en: 'Azerbaijan', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ألمانيا', name_en: 'Germany', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'أنجويلا', name_en: 'Anguilla', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'أورجواي', name_en: 'Uruguay', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'اريتريا', name_en: 'Eritrea', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'الأرجنتين', name_en: 'Argentina', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'الامارات العربية المتحدة', name_en: 'United Arab Emirates', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'البرازيل', name_en: 'Brazil', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'الجزائر', name_en: 'Algeria', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'السلفادور', name_en: 'El Salvador', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'السويد', name_en: 'Sweden', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'الفاتيكان', name_en: 'Vatican City State', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'الكونغو - برازافيل', name_en: 'Congo', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'المحيط الهندي البريطاني', name_en: 'British Indian Ocean Territory', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'المملكة العربية السعودية', name_en: 'Saudi Arabia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'الولايات المتحدة الأمريكية', name_en: 'United States', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'اليونان', name_en: 'Greece', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'باكستان', name_en: 'Pakistan', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'بربادوس', name_en: 'Barbados', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'بليز', name_en: 'Belize', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'بوركينا فاسو', name_en: 'Burkina Faso', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'بولينيزيا الفرنسية', name_en: 'French Polynesia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'بيرو', name_en: 'Peru', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'تركمانستان', name_en: 'Turkmenistan', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'توفالو', name_en: 'Tuvalu', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'زيمبابوي', name_en: 'Zimbabwe', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'زائير', name_en: 'Zaire', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزر فرجين الأمريكية', name_en: 'Virgin Islands (U.S.)', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزر الولايات المتحدة البعيدة الصغيرة', name_en: 'United States minor outlying islands', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سفالبارد وجان مايان', name_en: 'Svalbard and Jan Mayen Islands', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', name_en: 'South Georgia South Sandwich Islands', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سلوفاكيا', name_en: 'Slovakia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ساو تومي وبرينسيبي', name_en: 'Sao Tome and Principe', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'سانت فنسنت وغرنادين', name_en: 'Saint Vincent and the Grenadines', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'فلسطين', name_en: 'Palestine', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزيرة نورفوك', name_en: 'Norfolk Island', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'كاليدونيا الجديدة', name_en: 'New Caledonia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ناميبيا', name_en: 'Namibia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'منغوليا', name_en: 'Mongolia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ميكرونيزيا', name_en: 'Micronesia, Federated States of', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'كمبوديا', name_en: 'Cambodia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جمهورية افريقيا الوسطى', name_en: 'Central African Republic', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'كوستاريكا', name_en: 'Costa Rica', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جيبوتي', name_en: 'Djibouti', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'تيمور الشرقية', name_en: 'East Timor', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'فنلندا', name_en: 'Finland', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'فرنسا ، متروبوليتان', name_en: 'France, Metropolitan', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جرينادا', name_en: 'Grenada', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'غينيا بيساو', name_en: 'Guinea-Bissau', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزيرة هيرد وماكدونالد', name_en: 'Heard and Mc Donald Islands', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'كازاخستان', name_en: 'Kazakhstan', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'كوريا الجنوبية', name_en: 'Korea, Republic of', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'ليبيريا', name_en: 'Liberia', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'مدغشقر', name_en: 'Madagascar', code: '', currency: '', utc_time: '', is_published: true )
Country.create( name_ar: 'جزر المارشال', name_en: 'Marshall Islands', code: '', currency: '', utc_time: '', is_published: true )
